### ISSUE TITLE
Summarize Client's "Normal"

### ISSUE THREAD

**Issue by lydia-wu** [lydia-wu/cadence#28]
`Due: 2022-01-19, @12PM EDT`
`Timebox: 45 minutes`

- [ ] Summarize Client's "welcome back sketch" definitions of "Normal" (page 2) within a 1-page, typed document

### Note
(1) If you don't finish in 45 minutes, just post below what you have finished. This document will be valuable when @htyuki and @lydia-wu are querying, and it doesn't need to be clean or published--it just needs to be a quick, digestible set of bullets that we can reference.  
(2) This will also be valuable as you start to shape our simulated data (see Issue for more details) 

[2022-01-14 welcome back sketch discussion.pdf](https://github.com/lydia-wu/cadence/files/7875946/2022-01-14.welcome.back.sketch.discussion.pdf)

**Comment by lydia-wu** [comment]
### Phase 1: "Ducktape and Bandaid something together"
- [ ] hardcode some simulated data to pass over to Michael
- [ ] create some CSVs and string data: baby steps of what normal is
- [ ] "Hello World" every minute
- [ ] Device, Carrier, and Application are each producing a "Hello World" type message

### Phase 2 "A little more elegant"
- [ ] Use Python to write code that can be customized (columns, data parameters, etc)
- [ ] writing "Threads"

**Comment by hunter-alloway** [comment]
Attached are notes that I have incorporated from today's meeting with Mr. Stansell and his published content that he shared during our kickoff meeting on Friday, January 14th. 

The content is a summary of the events that will take place in the next coming days/weeks. To summarize, the idea is to have a simulation environment up and running as quickly as possible, using either Python or C# such that the team is not bottlenecked at the source of the operation. Once a simulated data environment is created, log filed in the form of CSV's will be offloaded from a cloud/server/platform to be further defined, and automatically send through instant messaging or email. The CSV file attached in this form of communication will contain all the details necessary to ingest and begin the process of flagging critical data and defining a healthy norm. It is imperative that we formulate a simulation process (does not have to look good, or function exactly as we would like) in order to continue with subsequent objectives. 

I will need help developing this code as this is a bigger task than we all were expecting. Regardless of the code complexity to define the content that will later be ingested, the simulation process involves creating a baseline code that requests information from a user and properly interfaces with the customer. 
 
Future goals that are not yet defined in the stakeholder requirements: Mr. Stansell would like the user to be interacting with this program on multiple interfaces, such as on a PC and potentially through a mobile application to be able to access the information easily.
[Cadence Sync-Up Recap_ Meeting with Mr. Stansell.pdf](https://github.com/lydia-wu/cadence/files/7908472/Cadence.Sync-Up.Recap_.Meeting.with.Mr.Stansell.pdf)
[Data Simulation Pathway.pdf](https://github.com/lydia-wu/cadence/files/7908473/Data.Simulation.Pathway.pdf)


Cheers,
Hunter Alloway
