### ISSUE TITLE
Sync: Lydia & Hunter Transition

### ISSUE THREAD

**Issue by lydia-wu** [lydia-wu/cadence#43]
Due `Wednesday 2022-02-16 12PM`

@lydia-wu : 
- [ ] Schedule a time with @hunter-alloway before Wednesday to walk through PBI design from #41 
- [ ] Drop any recorded notes in this issue

@hunter-alloway :
- [ ] Schedule a follow-up with @lydia-wu  as necessary
- [ ] After meeting, drop a comment in this issue confirming solid transition

**Comment by lydia-wu** [comment]
### Meeting Scheduled: `2022-02-14 @10:30-11:30AM, Monday`

### Agenda:
- [ ] pray
- [ ] walk through #41 completed design
- [ ] walk through @hunter-alloway's learning/questions
- [ ] rebuild #41 together (working lab session) to get a feel for PBI in practice

**Comment by lydia-wu** [comment]
Takeaway
- [ ] need to find a way to re-route data source @hunter-alloway 
- [ ] what is the finished product? We need a goal @biosguy
- [ ] PM --> high tasks/management @hunter-alloway
